version: "3"
services:
  mysql_db:
    container_name: mysql_db
    build:
      context: ./config/mysql
      dockerfile: Dockerfile
    volumes:
      - ${DATA_PATH}/mysql:/var/lib/mysql
      - ${PROJECT_PATH}:/var/www
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    command: --character-set-server=utf8 --collation-server=utf8_general_ci
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  phpmyadmin:
    restart: unless-stopped
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin:5
    environment:
      PMA_HOST: ${MYSQL_HOST}
    volumes:
      - /sessions
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  php:
    restart: unless-stopped
    container_name: php
    build:
      context: ./config/php
      dockerfile: Dockerfile.${CURRENT_ENV}
    volumes:
      - ${PROJECT_PATH}:/var/www/html
      - ${DATA_PATH}:/data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"

  caddy:
    restart: unless-stopped
    container_name: caddy
    build:
      context: ./config/caddy
      dockerfile: Dockerfile
    volumes:
      - ./config/caddy/Caddyfile.${CURRENT_ENV}:/etc/caddy/Caddyfile
      - ${DATA_PATH}/caddy:/data
      - ${PROJECT_PATH}:/var/www/html
    ports:
      - 80:80
      - 443:443
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "10"
